after-startup-command = ['exec-and-forget open -a Ghostty']
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'
    alt-shift-f = 'fullscreen'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-a = 'workspace A'
    alt-b = 'workspace B'
    alt-d = 'workspace D'
    alt-e = 'workspace E'
    alt-r = 'workspace R'
    alt-s = 'workspace S'
    alt-t = 'workspace T'
    alt-w = 'workspace W'
    alt-x = 'workspace X'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-a = 'move-node-to-workspace A'
    alt-shift-b = 'move-node-to-workspace B'
    alt-shift-d = 'move-node-to-workspace D'
    alt-shift-e = 'move-node-to-workspace E'
    alt-shift-r = 'move-node-to-workspace R'
    alt-shift-s = 'move-node-to-workspace S'
    alt-shift-t = 'move-node-to-workspace T'
    alt-shift-w = 'move-node-to-workspace W'
    alt-shift-g = 'move-node-to-workspace G'
    alt-shift-x = 'move-node-to-workspace X'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-0 = 'exec-and-forget ~/Development/dotfiles/toggle-ghostty-shader.sh negative'
    alt-9 = 'exec-and-forget ~/Development/dotfiles/toggle-ghostty-shader.sh starfield-colors'
    alt-8 = 'exec-and-forget ~/Development/dotfiles/toggle-ghostty-shader.sh dither'

    alt-g = 'workspace G'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
    b = ['exec-and-forget ~/Development/dotfiles/open-chrome-here.sh', 'mode main']
    t = ['exec-and-forget ~/Development/dotfiles/open-ghostty-here.sh', 'mode main']

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = ['move-node-to-workspace E', 'layout accordion']

[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = ['move-node-to-workspace E', 'layout accordion']

[[on-window-detected]]
if.app-id = 'NMPQX8QV9B.Earnit'
run = "move-node-to-workspace A"

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace G'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace S', 'layout accordion']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['move-node-to-workspace S', 'layout accordion']

[[on-window-detected]]
if.app-id = 'com.github.xournalpp'
run = "move-node-to-workspace X"

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = "move-node-to-workspace R"

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = ['move-node-to-workspace W', 'layout accordion']

[[on-window-detected]]
if.app-id = 'com.figma.Desktop.dua'
run = ['move-node-to-workspace D', 'layout accordion']

[[on-window-detected]]
if.app-id = 'com.mongodb.compass'
run = ['move-node-to-workspace D', 'layout accordion']

[[on-window-detected]]
if.app-id = 'org.pgadmin.pgadmin4'
run = ['move-node-to-workspace D', 'layout accordion']

[[on-window-detected]]
if.app-id = 'com.microsoft.StorageExplorer'
run = ['move-node-to-workspace D', 'layout accordion']

[[on-window-detected]]
if.app-id = 'org.filezilla-project.filezilla'
run = ['move-node-to-workspace D', 'layout accordion']

[[on-window-detected]]
if.app-id = 'com.docker.docker'
run = ['move-node-to-workspace D', 'layout accordion']
